[tool]
name = "stylua"
description = "Lua formatter"
capabilities = ["formatter"]

[tool.install.binary]
url = "https://github.com/JohnnyMorganz/StyLua/releases/download/v0.20.0/stylua-linux-x86_64.zip"
executable_name = "stylua"
[formatter]
command = "stylua"
