[language]
name = "markdown"
extensions = ["md", "markdown", "mdown", "mkd", "mkdn"]

[parser]
type = "wasm"
source = "build"
repo = "tree-sitter-grammars/tree-sitter-markdown"
download_url = "https://github.com/tree-sitter/tree-sitter-markdown/releases/latest/download/tree-sitter-markdown.wasm"

[lsp]
name = "marksman"
download_url = "https://github.com/artempyanykh/marksman/releases/latest/download/marksman-{os}-{arch}"
command = "marksman"
args = ["server"]

[sandbox]
compile_cmd = ""
run_cmd = ""
