[tool]
name = "ormolu"
description = "Haskell formatter"
capabilities = ["formatter"]

[tool.download]
url = "https://github.com/tweag/ormolu/releases/download/0.8.0.2/ormolu-x86_64-linux.zip"
executable_name = "ormolu"
[formatter]
command = "ormolu"
args = ["--mode", "inplace"]
