[tool]
name = "biome"
description = "Web project toolchain for formatting and linting"
capabilities = ["formatter", "linter"]
languages = ["javascript", "typescript", "json", "css", "vue", "svelte"]

[tool.download]
url = "https://github.com/biomejs/biome/releases/download/cli%2F1.9.3/biome-linux-x64"
executable_name = "biome"

[formatter]
command = "biome"
args = ["format", "--write", "{src}"]

[linter]
command = "biome"
args = ["lint", "--apply", "{src}"]
