[tool]
name = "biome"
description = "Web project toolchain for formatting and linting"
capabilities = ["formatter", "linter", "lsp"]

[tool.install.binary]
url = "https://github.com/biomejs/biome/releases/download/cli%2F1.9.3/biome-linux-x64"
executable_name = "biome"

[formatter]
command = "biome"
args = ["format", "--write"]

[linter]
command = "biome"
args = ["lint", "--apply"]

[lsp]
command = "biome"
args = ["lsp-proxy"]
